name: CI - Tests

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run Jest unit tests
        run: npx jest --runInBand



  functional-tests:
    runs-on: ubuntu-latest
    needs: unit-tests   # só roda se unit-tests PASSAR

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      # Instalar Google Chrome
      - name: Install Google Chrome 142
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: '142'


      # Instalar ChromeDriver compatível
      - name: Install ChromeDriver
        uses: nanmu42/chromedriver-installer@v1.1.0
        with:
          chrome-version: '142'

      # Xvfb para rodar Chrome headless
      - name: Install xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      # Subir servidor local antes do Selenium
      - name: Start Local Server
        run: |
          npx http-server -p 8080 &
          sleep 3

      # Executar Selenium com xvfb
      - name: Run Selenium Functional Tests
        env:
          SITE_URL: http://localhost:8080
        run: xvfb-run -a npm run test:functional
