name: CI - Tests

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run Jest unit tests
        run: npx jest --runInBand


  functional-tests:
    runs-on: ubuntu-latest
    needs: unit-tests  # só roda se os unit tests PASSAREM

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install


      # Instalar Chrome
      - name: Install Google Chrome 142
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: '142'

      # Instalar ChromeDriver correspondente
      - name: Install ChromeDriver
        uses: nanmu42/chromedriver-installer@v1.1.0
        with:
          chrome-version: '142'

      # Instalar Xvfb para Chrome headless
      - name: Install xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb


      # SUBIR SERVIDOR LOCAL SERVINDO A RAIZ
      - name: Start Local Server
        run: |
          echo "Iniciando servidor..."
          nohup npx http-server -p 8080 > server.log 2>&1 &
          sleep 5
          echo "Conteúdo do server.log:"
          cat server.log || true

      - name: Test connection to server
        run: |
          echo "Testando curl..."
          curl -v http://localhost:8080 || exit 1


      # RODAR SELENIUM FUNCIONAL
      - name: Run Selenium Functional Tests
        env:
          SITE_URL: http://localhost:8080
        run: xvfb-run -a npm run test:functional
